version: '3.8'

services:
  finance:
    ports: 
      - "8090:80"
    build:
      context: ./environment/standard
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    container_name: Finance-Model-Research
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - TZ=Asia/Tokyo
    env_file:
      - .env
    volumes:
      - ../:/root/src
    working_dir: /root/src
    runtime: nvidia
    tty: true
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 100g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
