version: '3.8'

services:
  python:
    ports: 
    #Container:80 local:8100
      - "8100:80"
    build:
      context: ./environment/MoriMori
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    container_name: MoriMoriEnvironment
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - TZ=Asia/Tokyo
    env_file:
      - .env
    volumes:
    #Container:/root/src local:../
      - ../:/root/src
    working_dir: /root/src
    runtime: nvidia
    tty: true
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 100g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Rust:
  #   build:
  #     context: ./environment/Rust
  #     dockerfile: Dockerfile
  #     args:
  #       - HTTP_PROXY=${HTTP_PROXY}
  #       - HTTPS_PROXY=${HTTPS_PROXY}
  #   container_name: Rust-Service
  #   environment:
  #     - http_proxy=$HTTP_PROXY
  #     - https_proxy=$HTTPS_PROXY
  #     - TZ=Asia/Tokyo
  #   env_file:
  #     - .env
  #   volumes:
  #     - ../:/root/src
  #   working_dir: /root/src
  #   tty: true
  #   restart: "no"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 8g